name: CI Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Pobranie repozytorium
        uses: actions/checkout@v3
      - name: Instalacja zależności
        run: mvn dependency:resolve
      - name: Budowanie projektu
        run: mvn compile
      - name: Uruchomienie testów
        run: mvn test
